runtime: python27
threadsafe: yes
api_version: 1

handlers:
- url: /static
  static_dir: static/
- url: /vendor
  static_dir: vendor/

- url: .*
  script: login.app

libraries:
- name: jinja2
  version: latest
